import axios from "axios";
import {
  upload
} from "../../lib/upload.js";
import {
  simpleQuoted
} from "../../lib/quoted.js";
export default {
  name: "fixart",
  aliases: ["fixart"],
  description: "AI Image Generator / Editor menggunakan FixArt (T2I & I2I)",
  category: "AI",
  example: "fixart <prompt> [--state <token>] atau reply gambar dengan caption fixart <prompt>",
  execute: async (sock, ctx, msg) => {
    try {
      let text = ctx.args?.join(" ")?.trim() || "";
      if (!text && ctx.text) {
        const raw = ctx.text.trim();
        const firstWord = raw.split(/\s+/)[0].toLowerCase();
        if (firstWord.endsWith("fixart")) {
          text = raw.slice(firstWord.length).trim();
        }
      }
      const isMedia = ctx.isMedia || ctx.quoted?.isMedia;
      const prefix = ctx.prefix || ".";
      const botName = global.bot?.name || "WudysoftBot";
      const quotedMsg = typeof simpleQuoted === "function" ? simpleQuoted(ctx) : msg;
      if (!text && !isMedia) {
        return ctx.reply(`🎨 *FIXART AI GENERATOR & EDITOR*\n\n` + `• *Text-to-Image (T2I):*\n` + `  👉 \`${prefix}fixart cat with sunglasses\`\n\n` + `• *Image-to-Image (I2I):*\n` + `  👉 Reply/kirim gambar dengan: \`${prefix}fixart add hat\`\n\n` + `• *Dengan State (Lanjutan Edit):*\n` + `  👉 \`${prefix}fixart add sunglasses --state <state_token>\``);
      }
      await ctx.react("⏳");
      let prompt = text;
      let state = "";
      if (/--state\s+([^\s]+)/i.test(prompt)) {
        const match = prompt.match(/--state\s+([^\s]+)/i);
        if (match) state = match[1];
        prompt = prompt.replace(/--state\s+[^\s]+/gi, "").trim();
      }
      const body = {
        prompt: prompt || "enhance quality, masterpiece, 4k"
      };
      if (isMedia) {
        const buffer = await ctx.download();
        if (!buffer || !Buffer.isBuffer(buffer)) {
          await ctx.react("❌");
          return ctx.reply("❌ Gagal mengunduh media dari pesan.");
        }
        const uploadRes = await upload(buffer);
        if (!uploadRes?.status || !uploadRes?.url) {
          await ctx.react("❌");
          return ctx.reply(`❌ Gagal mengunggah gambar: ${uploadRes?.message || "Server upload error"}`);
        }
        body.image = uploadRes.url;
      }
      if (state) {
        body.state = state;
      }
      const {
        data
      } = await axios.post("https://wudysoft.my.id/api/ai/fixart", body, {
        headers: {
          "Content-Type": "application/json",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        },
        timeout: 6e4
      });
      const resultImage = data?.result || data?.resultUrl || data?.image;
      if (!data || data.status !== true && data.status !== "success" || !resultImage) {
        await ctx.react("❌");
        return ctx.reply(`❌ Gagal memproses gambar: ${data?.message || "API tidak mengembalikan hasil."}`);
      }
      const mode = body.image ? "IMAGE-TO-IMAGE" : "TEXT-TO-IMAGE";
      const returnedState = data.state || "";
      const bodyText = `🎨 *FIXART AI COMPLETED*\n\n` + `📝 *Prompt:* ${prompt || "-"}\n` + `🎭 *Mode:* \`${mode}\`\n\n` + `_💡 Klik tombol copy di bawah untuk melanjutkan pengeditan gambar ini._`;
      const footerText = `${botName} • FixArt AI`;
      const buttons = [];
      if (returnedState) {
        const nextCommand = `${prefix}fixart <tulis_prompt_edit_lanjutan> --state ${returnedState}`;
        buttons.push({
          name: "cta_copy",
          display_text: "📋 Salin Lanjutan Edit",
          copy_code: nextCommand
        }, {
          name: "cta_copy",
          display_text: "🔑 Salin State Token",
          copy_code: returnedState
        });
      }
      if (typeof ctx.sendCta === "function") {
        await ctx.sendCta(bodyText, footerText, buttons, {
          title: `乂 FIXART AI - ${mode} 乂`,
          subtitle: `Generated by FixArt`,
          media: resultImage,
          quoted: quotedMsg
        });
      } else {
        await sock.sendMessage(ctx.id, {
          image: {
            url: resultImage
          },
          caption: bodyText
        }, {
          quoted: quotedMsg
        });
      }
      await ctx.react("✅");
    } catch (error) {
      await ctx.react("❌");
      const errMsg = error.response?.data?.message || error.response?.data?.error || (typeof error.response?.data === "string" ? error.response.data : null) || error.message;
      ctx.reply(`❌ Terjadi kesalahan: ${errMsg}`);
    }
  }
};