import axios from "axios";
import {
  upload
} from "../../lib/upload.js";
import {
  simpleQuoted
} from "../../lib/quoted.js";
export default {
  name: "magiceraser",
  aliases: ["magiceraser", "magicerase", "me2i"],
  description: "AI Image Generator & Editor menggunakan MagicEraser (T2I & I2I)",
  category: "AI",
  example: "magiceraser <prompt> atau reply gambar dengan caption magiceraser <prompt>",
  execute: async (sock, ctx, msg) => {
    try {
      let text = ctx.args?.join(" ")?.trim() || "";
      if (!text && ctx.text) {
        const raw = ctx.text.trim();
        const firstWord = raw.split(/\s+/)[0].toLowerCase();
        if (firstWord.endsWith("magiceraser") || firstWord.endsWith("magicerase")) {
          text = raw.slice(firstWord.length).trim();
        }
      }
      const isMedia = ctx.isMedia || ctx.quoted?.isMedia;
      const prefix = ctx.prefix || ".";
      const botName = global.bot?.name || "WudysoftBot";
      const quotedMsg = typeof simpleQuoted === "function" ? simpleQuoted(ctx) : msg;
      if (!text && !isMedia) {
        return ctx.reply(`✨ *MAGICERASER AI GENERATOR & EDITOR*\n\n` + `• *Text-to-Image (T2I):*\n` + `  👉 \`${prefix}magiceraser cyberpunk anime girl, highly detailed\`\n\n` + `• *Image-to-Image (I2I):*\n` + `  👉 Reply/kirim gambar dengan: \`${prefix}magiceraser filter anime style\``);
      }
      await ctx.react("⏳");
      const params = {
        prompt: text || "enhance quality, masterpiece, 4k"
      };
      if (isMedia) {
        const buffer = await ctx.download();
        if (!buffer || !Buffer.isBuffer(buffer)) {
          await ctx.react("❌");
          return ctx.reply("❌ Gagal mengunduh media dari pesan.");
        }
        const uploadRes = await upload(buffer);
        if (!uploadRes?.status || !uploadRes?.url) {
          await ctx.react("❌");
          return ctx.reply(`❌ Gagal mengunggah gambar: ${uploadRes?.message || "Server upload error"}`);
        }
        params.image = uploadRes.url;
      }
      const {
        data
      } = await axios.get("https://wudysoft.my.id/api/ai/magiceraser/v2", {
        params: params,
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        },
        timeout: 6e4
      });
      const resultImage = Array.isArray(data?.result) ? data.result[0] : data?.result || data?.image;
      if (!data || data.status !== true || !resultImage) {
        await ctx.react("❌");
        return ctx.reply(`❌ Gagal memproses gambar: ${data?.message || "API tidak mengembalikan hasil."}`);
      }
      const mode = data?.type ? data.type.toUpperCase() : params.image ? "IMAGE-TO-IMAGE" : "TEXT-TO-IMAGE";
      const modelUsed = data?.model_used || "magiceraser_v1";
      const bodyText = `✨ *MAGICERASER AI COMPLETED*\n\n` + `📝 *Prompt:* ${params.prompt}\n` + `🎭 *Mode:* \`${mode}\`\n` + `🤖 *Model:* \`${modelUsed}\`\n` + (data?.job_id ? `🆔 *Job ID:* \`${data.job_id}\`\n` : "");
      const footerText = `${botName} • MagicEraser AI`;
      if (typeof ctx.sendCta === "function") {
        await ctx.sendCta(bodyText, footerText, [], {
          title: `乂 MAGICERASER AI - ${mode} 乂`,
          subtitle: `Generated by MagicEraser`,
          media: resultImage,
          quoted: quotedMsg
        });
      } else {
        await sock.sendMessage(ctx.id, {
          image: {
            url: resultImage
          },
          caption: bodyText
        }, {
          quoted: quotedMsg
        });
      }
      await ctx.react("✅");
    } catch (error) {
      await ctx.react("❌");
      const errMsg = error.response?.data?.message || error.response?.data?.error || (typeof error.response?.data === "string" ? error.response.data : null) || error.message;
      ctx.reply(`❌ Terjadi kesalahan: ${errMsg}`);
    }
  }
};