import {
  simpleQuoted
} from "../../lib/quoted.js";
export default {
  name: "code",
  aliases: ["snippet", "highlight", "codesnippet", "js"],
  description: "Format dan tampilkan blok kode dengan syntax highlighting (NOVA / Meta AI)",
  category: "Developer",
  execute: async (sock, ctx, msg) => {
    try {
      const supportedLanguages = ["javascript", "js", "typescript", "ts", "python", "py", "html", "css", "json", "php", "java", "cpp", "c", "csharp", "go", "golang", "rust", "sql", "bash", "sh", "markdown"];
      let language = "javascript";
      let codeContent = "";
      const quotedRaw = ctx.quoted?.text || ctx.quoted?.caption || ctx.quoted?.body;
      const quotedText = typeof quotedRaw === "string" ? quotedRaw.trim() : "";
      if (quotedText) {
        const firstArg = (ctx.args?.[0] || "").toLowerCase();
        if (supportedLanguages.includes(firstArg)) {
          language = firstArg;
        }
        codeContent = quotedText;
      } else if (ctx.query) {
        const lines = ctx.query.trim().split("\n");
        const firstWord = (lines[0].split(/\s+/)[0] || "").toLowerCase();
        if (supportedLanguages.includes(firstWord)) {
          language = firstWord;
          if (lines.length > 1) {
            codeContent = lines.slice(1).join("\n").trim();
          } else {
            codeContent = ctx.query.slice(firstWord.length).trim();
          }
        } else {
          codeContent = ctx.query.trim();
        }
      }
      if (!codeContent) {
        return ctx.reply(`💻 *AI CODE SNIPPET HIGHLIGHTER*\n\n` + `📌 *Cara Penggunaan:*\n` + `• *${ctx.prefix || "."}code <bahasa> <kode>*\n` + `• Atau reply teks kode dengan: *${ctx.prefix || "."}code <bahasa>*\n\n` + `💡 *Contoh:*\n` + `${ctx.prefix || "."}code javascript\n` + `const greeting = "Hello World";\n` + `console.log(greeting);`);
      }
      await ctx.react?.("⏳");
      const langMap = {
        js: "javascript",
        ts: "typescript",
        py: "python",
        sh: "bash",
        golang: "go"
      };
      if (langMap[language]) language = langMap[language];
      codeContent = codeContent.replace(/^```[a-zA-Z]*\n?/, "").replace(/```$/, "").trim();
      const lineCount = codeContent.split("\n").length;
      const charCount = codeContent.length;
      const quotedMsg = typeof simpleQuoted === "function" ? simpleQuoted(ctx) || msg : msg;
      const targetJid = ctx.chat || ctx.id;
      await ctx.sendCode(codeContent, language, {
        jid: targetJid,
        quoted: quotedMsg,
        header: `📝 *${language.toUpperCase()} Snippet* (${lineCount} Baris • ${charCount} Karakter)`,
        footer: `💡 _Ketuk atau salin langsung blok kode di atas._`,
        disclaimer: "Generated by Meta AI Code Engine"
      });
      await ctx.react?.("✨");
    } catch (error) {
      console.error("[Code Command Error]", error);
      await ctx.react?.("❌");
      await ctx.reply(`❌ *Code Highlighter Error:* ${error?.message || error}`);
    }
  }
};